# Generated by Django 5.2.3 on 2025-06-28 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Введите название курса", max_length=250, verbose_name="Курс")),
                (
                    "preview_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте картинку",
                        null=True,
                        upload_to="lms/course_preview_picture/",
                        verbose_name="Превью (картинка)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Укажите описание курса", null=True, verbose_name="Описание курса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Введите название урока", max_length=250, verbose_name="Урок")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Укажите описание урока", null=True, verbose_name="Описание урока"
                    ),
                ),
                (
                    "preview_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте картинку",
                        null=True,
                        upload_to="lms/lesson_preview_picture/",
                        verbose_name="Превью (картинка)",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Добавьте ссылку на видео", null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите курс",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
